import numpy as np 
array_x= np.linspace(-10, 10, 50).astype(float)
print(array_x)
maxi_x = np.max(array_x)
mini_x = np.min(array_x)
print()
print(f'Valor máximo: {maxi_x:.2f}, valor mínimo: {mini_x:.2f}')
print()
array_y = np.array([n**2 for n in array_x]).astype(float)
print(array_y)
maxi_y = np.max(array_y)
mini_y = np.min(array_y)
print()
print(f'Valor máximo: {maxi_y:.2f}, valor mínimo: {mini_y:.2f}')
